
import { Roboto } from 'next/font/google'
import "./globals.css";



const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: "My-Nextjs-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <div className='min-h-screen'> {children}</div>

        <div>
          <footer className='text-center bg-gray-500 py-5'>This is fotter</footer>
        </div>
      </body>
    </html>
  );
}
